configcat/js-ssr-sdk

package-lock.json, samples/nuxt-ssr/package-lock.json, samples/nuxt-ssr/package.json
Updated dependencies and nuxt sample.
=> [Merge and release please] Updating dependencies and sample app

package-lock.json, package.json, samples/nuxt-ssr/package-lock.json, samples/nuxt-ssr/package.json
=> Security update

package-lock.json, package.json
=> Updating karma

package-lock.json, package.json
=> September security updates

package-lock.json, package.json
Updating configcat-common and axios to the latest.
=> February security review

package-lock.json, package.json, src/ConfigFetcher.ts
Use latest common & the new fetcher API.
=> Use latest common & the new fetcher API

package-lock.json, package.json, src/index.ts, test/IndexTests.ts, test/IntegrationTests.ts
Export factory function for flag overrides.
=> Export factory function for flag overrides

.npmignore, gulpfile.js, package-lock.json, package.json, src/ConfigFetcher.ts, src/Version.ts, src/index.ts
Passing the real SDK version and type to common-js.
=> Sdk Version fix

README.md
Sensitive information handling and browser compatibility
=> Sensitiveandbrowsercompatibility

package-lock.json, package.json, src/ConfigFetcher.ts
Add the `If-None-Match` header to the request headers when the SDK is not running in browser.
=> Re-add If-None-Match header

.npmignore, README.md, package-lock.json, package.json, samples/nuxt-ssr/package-lock.json, samples/nuxt-ssr/package.json
=> Prepares v6.0.0 release

samples/nuxt-ssr/package-lock.json, samples/nuxt-ssr/package.json
Updates samples to use the newly released version
=> Updates samples to use the newly released version

package-lock.json
February 2023 security updates
=> February 2023 security updates

CHANGELOG.md, README.md, package-lock.json, package.json, src/index.ts
=> Prepare v7.0.0 release

package-lock.json, package.json
=> Prepare v7.0.1 release

package-lock.json, package.json
=> [security] Axios Cross-Site Request Forgery Vulnerability 

package.json
=> [skip ci] Update package.json

samples/nuxt-ssr/package-lock.json, samples/nuxt-ssr/package.json
=> Update samples to v8.0.0

.vscode/settings.json, package-lock.json, package.json
=> Prepare v8.4.0 release

package-lock.json, package.json
Prepare v8.4.1 release (for security fix #81)
=> Prepare v8.4.1 release

.github/workflows/js-ssr-ci.yml, package-lock.json, package.json
=> Prepare v8.4.3 release

package-lock.json, package.json
April 2025 security updates
https://trello.com/c/Lpkeutq8
n/a
n/a
=> April 2025 security updates
